# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.0.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install packages
          command: npm install

      - run: 
          name: Build the app
          command: npm run ci-build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run the test
          command: npm test
      - run: # Install the AWS CLI if it is not already included in the docker image
          name: Install awscli 
          command: sudo apt-get -y -qq install awscli
      - run: # Deploy to S3 using the sync command
          name: Deploy to S3
          command: aws s3 sync client/build/ s3://hyg-test

  deploy:
    docker:
      - image: circleci/node:12.0.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "75:a0:e1:53:07:b9:ae:0b:77:2c:06:27:bc:6b:e0:21"
      - run:
          name: check ssh keys
          command: ssh-add -l
      - run:
          name: Deploy Changes To EC2
          command: ../scripts/build.sh
workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      #     filters:
      #         branches:
      #           only:
      #             - master